apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: homework
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       8000;
          server_name  localhost;
          location / {
            root   /homework;
            index  index.html;
        }
          location /metrics.html {
            alias   /homework/metrics.html;
        }
      }
    }
