apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otus-webserver-pvc
  namespace: homework
spec:
  storageClassName: "edustorageclass"
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
