apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  initContainers:
    - name: init
      image: busybox:1.36.1
      command:
        [
          "sh",
          "-c",
          wget -P /init https://storage.yandexcloud.net/skolarium-files/index.html,
        ]
      volumeMounts:
        - mountPath: /init
          name: empty-volume
  containers:
    - name: nginx-otus
      image: oshormidis/otus_nginx:0.0.2
      lifecycle:
        preStop:
          exec:
            command: ["sh", "-c", "sleep 5 && rm /homework/index.hml"]
      ports:
        - containerPort: 8000
      volumeMounts:
        - mountPath: /homework
          name: empty-volume
  volumes:
    - name: empty-volume
      emptyDir: {}
